/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDataTable: typeof import('./components/AppDataTable.vue')['default']
    AppDialog: typeof import('./components/AppDialog.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BackupDialog: typeof import('./components/BackupDialog.vue')['default']
    BusinessConfigDialog: typeof import('./components/BusinessConfigDialog.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    EmployeeDialog: typeof import('./components/EmployeeDialog.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FormField: typeof import('./components/FormField.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IMdiBank: typeof import('~icons/mdi/bank')['default']
    IMdiBookOpenPageVariant: typeof import('~icons/mdi/book-open-page-variant')['default']
    IMdiCalculator: typeof import('~icons/mdi/calculator')['default']
    IMdiCalendarCheck: typeof import('~icons/mdi/calendar-check')['default']
    IMdiCashMultiple: typeof import('~icons/mdi/cash-multiple')['default']
    IMdiChartBox: typeof import('~icons/mdi/chart-box')['default']
    IMdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    IMdiClipboardTextOutline: typeof import('~icons/mdi/clipboard-text-outline')['default']
    IMdiDatabaseImport: typeof import('~icons/mdi/database-import')['default']
    IMdiDownload: typeof import('~icons/mdi/download')['default']
    IMdiFileCertificate: typeof import('~icons/mdi/file-certificate')['default']
    IMdiFileDocumentOutline: typeof import('~icons/mdi/file-document-outline')['default']
    IMdiFileExcel: typeof import('~icons/mdi/file-excel')['default']
    IMdiFileImport: typeof import('~icons/mdi/file-import')['default']
    IMdiHistory: typeof import('~icons/mdi/history')['default']
    IMdiInformationOutline: typeof import('~icons/mdi/information-outline')['default']
    IMdiPackageVariant: typeof import('~icons/mdi/package-variant')['default']
    IMdiPercent: typeof import('~icons/mdi/percent')['default']
    IMdiTableEye: typeof import('~icons/mdi/table-eye')['default']
    IMdiUpload: typeof import('~icons/mdi/upload')['default']
    IMdiWarehouse: typeof import('~icons/mdi/warehouse')['default']
    ImportPreview: typeof import('./components/ImportPreview.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LineItemsEditor: typeof import('./components/LineItemsEditor.vue')['default']
    PayrollTable: typeof import('./components/PayrollTable.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./components/SectionCard.vue')['default']
    Select: typeof import('primevue/select')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
